#!/bin/sh

echo -n Try to bring usb0 interface up......>/dev/ttySAC0

modprobe g_ether
ifconfig usb0 192.168.2.55 up
route add default gw 192.168.2.1
echo "nameserver 192.168.2.1" > /etc/resolv.conf

