#!/bin/sh

echo -n Try to bring usb0 interface up... >/dev/ttySAC0

modprobe g_ether

if [ -f /etc/usb0-setting ] ; then
	source /etc/usb0-setting
	ifconfig usb0 down
	ifconfig usb0 $IP netmask $Mask up
	route add default gw $Gateway
	echo nameserver $DNS > /etc/resolv.conf
else
	echo -n Failed to bring usb0 interface up... >/dev/ttySAC0
fi

echo -n Done... >/dev/ttySAC0

